### ISSUE TITLE
keyval.splitN is not a function

### ISSUE THREAD

**Issue by gaoyifan** [ustclug/ustcmirror#6]
mirrors2.s.u.o上运行：`ustcmirror repo-update ubuntu 'envs.RSYNC_HOST=archive.ubuntu.com'`

```
/home/knight/Yuki/packages/yuki-cli/index.js:355
    const [k, v] = keyval.splitN('=', 1) // See `patch.js`
                          ^

TypeError: keyval.splitN is not a function
    at Command.program.command.description.action (/home/knight/Yuki/packages/yuki-cli/index.js:355:27)
    at Command.listener (/home/knight/Yuki/packages/yuki-cli/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:194:7)
    at Command.parseArgs (/home/knight/Yuki/packages/yuki-cli/node_modules/commander/index.js:615:12)
    at Command.parse (/home/knight/Yuki/packages/yuki-cli/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/home/knight/Yuki/packages/yuki-cli/index.js:606:9)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
    at bootstrap_node.js:540:3
```

**Comment by knight42** [comment]
Fixed by https://github.com/ustclug/ustcmirror/commit/f27ae4f86b0c3b47c9def552405cbd3ccd897f1a
